feat: Support setting the horizontal and vertical screen orientation …
Tencent/Shadow pull request #1258
Opened 2023-11-27 09:27 UTC by AntonioShare

Support setting the horizontal and vertical screen orientation in the plugin's AndroidManifest. And set the TestActivityOrientation direction in AndroidManifest to landscape

2023-11-27 09:28 UTC, tencent-adm commented
[![CLA assistant check](https://cla.opensource.tencent.com/pull/badge/not_signed)](https://cla.opensource.tencent.com/Tencent/Shadow?pullRequest=1258) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/Shadow?pullRequest=1258) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/Shadow?pullRequest=1258) it.</sub>

2023-11-27 10:03 UTC, shifujun commented
感谢贡献代码。这个PR看起来很干净，应该很好合入。目前CI检查已经有点报错。你可以自己修改提交，或者我可以晚些帮你改好合入。

2023-11-27 10:36 UTC, AntonioShare commented
> CI会检查每个提交，而不仅仅是最终状态。所以你需要rebase提交，然后force push。

现在应该可以了

2023-11-27 10:42 UTC, shifujun commented
> > CI会检查每个提交，而不仅仅是最终状态。所以你需要rebase提交，然后force push。
> 
> 现在应该可以了

你看这个PR还是包含两个提交，这应该是不对的。你应该把第二个fix提交合并到最初的提交中。同时修改最初的提交的commit message，使其通过检查。code format检查确实是只检查最终代码，但是commit message检查是要检查每一个提交的。

2023-11-27 10:42 UTC, AntonioShare commented
> CI会检查每个提交，而不仅仅是最终状态。所以你需要rebase提交，然后force push。

非常抱歉，似乎还有问题，我将再次检查一下代码在进行force push

2023-11-27 10:43 UTC, AntonioShare commented
> > > CI会检查每个提交，而不仅仅是最终状态。所以你需要rebase提交，然后force push。
> > 
> > 
> > 现在应该可以了
> 
> 你看这个PR还是包含两个提交，这应该是不对的。你应该把第二个fix提交合并到最初的提交中。同时修改最初的提交的commit message，使其通过检查。code format检查确实是只检查最终代码，但是commit message检查是要检查每一个提交的。

好的，非常抱歉。我这就更改

2023-11-27 10:43 UTC, shifujun commented
另外你如果愿意自己动手的话，也可以在自己fork的仓库开启github action。这样可以在自己的仓库触发同样的CI检查。

2023-11-27 10:59 UTC, AntonioShare commented
> 另外你如果愿意自己动手的话，也可以在自己fork的仓库开启github action。这样可以在自己的仓库触发同样的CI检查。

非常抱歉，最后一次多了一个.字符忘记删，已修正

2023-11-27 13:02 UTC, AntonioShare commented
> 另外你如果愿意自己承担的话，也可以在自己fork的仓库开启github操作。这样就可以在自己的仓库触发同样的CI检查。

检测已经通过，代码似乎还需您review一下才能进去

2023-11-27 13:03 UTC, shifujun requested changes
两个问题。1是前面评论的3次取同一域变量的问题。2是commit message可以清楚的写出来是怎么support的，即判断requestedOrientation和插件manifest中不一致时主动设置它。

2023-11-27 13:03 UTC, shifujun commented on projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/delegates/ShadowActivityDelegate.kt
> +        }
`pluginActivityInfo.screenOrientation`重复出现了3次。应该先赋值给局部变量，再使用，表达出3处值是同一个不变值。

2023-11-28 01:07 UTC, AntonioShare commented on projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/delegates/ShadowActivityDelegate.kt
> +        }
好的，已修正，重新force push了

2023-11-28 01:12 UTC, AntonioShare commented on projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/delegates/ShadowActivityDelegate.kt
> +        }
不好意思，我没注意到body也限制了100字符，我刚重新修正重新提交了

2023-11-28 02:34 UTC, shifujun approved these changes

2023-11-28 02:34 UTC, merged

2023-11-28 02:35 UTC, shifujun commented
done🎉