:wrench: 修复插件中provider的grantUriPermissions为false但shadow默认为true的问题
Tencent/Shadow pull request #859
Opened 2022-03-22 08:08 UTC by SpaceQ-Z

修复https://github.com/Tencent/Shadow/issues/855中遇到的问题
修复插件中provider的grantUriPermissions为false但shadow默认为true的问题

2022-03-22 08:57 UTC, shifujun commented on projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/managers/PluginContentProviderManager.kt
> +import android.util.Log
未使用的import需要去掉。

2022-03-22 09:03 UTC, SpaceQ-Z commented on projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/managers/PluginContentProviderManager.kt
> +import android.util.Log
恩，去掉了，调试的时候删除了调试代码忘了删导包了

2022-03-22 09:11 UTC, shifujun commented
还有一个问题，你的commit的author并不是你当前提PR的账号。如果合并进来，无法自动关联你为贡献者。

2022-03-22 10:18 UTC, SpaceQ-Z commented
好的，首次为开源做贡献，已经更改了

2022-03-23 03:03 UTC, shifujun commented
Github Actions 卡在Queued状态了。看起来有bug：https://github.community/t/cant-cancel-github-action-workflow/16060/43

我试试关了这个PR重开怎么样。

2022-03-23 03:10 UTC, shifujun requested changes
代码没什么问题。就是没有format呀。可以看到这里检查失败了：https://github.com/Tencent/Shadow/runs/5654420771?check_suite_focus=true

比如: 
```
-        const val grantUriPermissions="android:grantUriPermissions"
+        const val grantUriPermissions = "android:grantUriPermissions"
```
就是提示这里format之后有这些空格的变化。

2022-03-23 03:15 UTC, SpaceQ-Z commented
> Github Actions 卡在Queued状态了。看起来有bug：https://github.community/t/cant-cancel-github-action-workflow/16060/43
> 
> 我试试关了这个PR重开怎么样。

可以，那我重提一个PR吧

2022-03-23 03:17 UTC, shifujun commented
> > Github Actions 卡在Queued状态了。看起来有bug：https://github.community/t/cant-cancel-github-action-workflow/16060/43
> > 我试试关了这个PR重开怎么样。
> 
> 可以，那我重提一个PR吧

不用了，重新打开后已经正常了。你应该能看到那些Check已经跑起来了。

2022-03-23 03:20 UTC, closed without merging